name: abce
description: A Flutter app for eBooks

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.4.3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^7.4.0
  package_info: ^2.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.3
  connectivity_plus: ^5.0.2
  dio: ^5.1.2
  file_picker: ^4.3.3
  image_gallery_saver: ^2.0.3

  fluttertoast: ^8.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  path: ^1.8.2
  path_provider: ^2.0.3
  permission_handler: ^10.2.0
  riverpod_annotation: ^2.1.1
  sembast: ^3.4.5
  sembast_web: ^2.1.3
  share_plus: ^4.0.4
  shared_preferences: ^2.1.1
  xml2json: ^5.3.1
  carousel_slider: ^4.1.0
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.18.0
  webview_flutter: ^3.0.4
  provider: ^6.0.5
  flutter_native_splash: ^2.3.6
  flutter_screenutil: ^5.9.0
  r_upgrade: ^0.4.2

dependency_overrides:
  collection: ^1.17.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/image/
    - assets/images/img/
flutter_intl:
  enabled: true
